package org.unibl.etf.efikas.models.responses.errors;

public enum ApiErrorCode {
    VALIDATION_FAILED,
    MALFORMED_REQUEST,
    BUSINESS_RULE_VIOLATION,
    AUTHENTICATION_REQUIRED,
    INVALID_CREDENTIALS,
    ACCESS_DENIED,
    RESOURCE_NOT_FOUND,
    RESOURCE_CONFLICT,
    DATA_INTEGRITY_CONFLICT,
    UPSTREAM_SERVICE_ERROR,
    INTERNAL_ERROR
}
