import DateTimePicker from "@/src/components/organisms/DateTimePicker/DateTimePicker";
import { AvailabilityBadge, DetailRow, formatTaskDate, LoadMore, PriorityBadge, TaskStatusBadge, WorkflowButton, WorkflowCard, WorkflowChip, WorkflowState } from "@/src/components/screens/TaskWorkflowScreen/TaskWorkflowUi";
import { useAvailableTasks, useMyTasks } from "@/src/hooks/useTaskWorkflows";
import { useProfile } from "@/src/hooks/useProfile";
import { useAttendanceHistory, useAvailabilityOverrides, useCancelLeaveRequest, useClearAvailabilityOverride, useClockIn, useClockOut, useCreateAvailabilityOverride, useCreateLeaveRequest, useEndBreak, useLeaveRequests, useStartBreak, useWorkerAvailability } from "@/src/hooks/useWorkforce";
import { useTheme } from "@/src/providers/ThemeProvider";
import { AvailabilityOverride, AttendanceSession, LeaveRequest, OperationalTask, TaskStatus, WorkerAvailability } from "@/src/types/types";
import { getUserFacingErrorMessage } from "@/src/util/apiError";
import { router } from "expo-router";
import { useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

type WorkerSection = "overview" | "available" | "mine" | "attendance" | "overrides" | "leave";
const sections: WorkerSection[] = ["overview", "available", "mine", "attendance", "overrides", "leave"];
const taskStatuses: TaskStatus[] = ["ASSIGNED", "IN_PROGRESS", "BLOCKED", "COMPLETED", "CANCELLED"];

export default function WorkerDashboardScreen() {
  const { t } = useTranslation();
  const { Colors } = useTheme();
  const [section, setSection] = useState<WorkerSection>("overview");
  const availability = useWorkerAvailability();
  const profile = useProfile();
  const refresh = () => void Promise.all([availability.refetch(), profile.refetch()]);
  return <SafeAreaView edges={["bottom"]} style={[styles.screen, { backgroundColor: Colors.screenBackground }]}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <View style={styles.heading}><Text style={[styles.title, { color: Colors.textPrimary }]}>{t("taskWorkforce.worker.homeTitle")}</Text><Text style={{ color: Colors.textSecondary }}>{profile.profile ? t("taskWorkforce.worker.greeting", { name: profile.profile.name }) : t("taskWorkforce.worker.homeSubtitle")}</Text>{availability.data ? <AvailabilityBadge status={availability.data.status} /> : null}</View>
    {availability.isPending ? <WorkflowState icon="LoaderCircle" title={t("taskWorkforce.common.loading")} description={t("taskWorkforce.worker.loadingStatus")} /> : availability.isError ? <WorkflowState icon="CircleAlert" title={t("taskWorkforce.common.errorTitle")} description={t("taskWorkforce.worker.statusError")} actionLabel={t("taskWorkforce.common.retry")} onAction={refresh} /> : null}
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{sections.map((item) => <WorkflowChip key={item} label={t(`taskWorkforce.worker.sections.${item}`)} selected={section === item} onPress={() => setSection(item)} />)}</ScrollView>
    {section === "overview" ? <WorkerOverview availability={availability.data} onNavigate={setSection} /> : null}
    {section === "available" ? <AvailableTasks /> : null}
    {section === "mine" ? <MyTasks /> : null}
    {section === "attendance" ? <Attendance availability={availability.data} /> : null}
    {section === "overrides" ? <Overrides /> : null}
    {section === "leave" ? <LeaveRequests /> : null}
  </ScrollView></SafeAreaView>;
}

function WorkerOverview({ availability, onNavigate }: { availability?: WorkerAvailability; onNavigate: (section: WorkerSection) => void }) {
  const { t, i18n } = useTranslation();
  const { Colors } = useTheme();
  const available = useAvailableTasks({ size: 1, sort: "updatedAt,desc" });
  const assigned = useMyTasks({ status: "ASSIGNED", size: 1, sort: "updatedAt,desc" });
  const inProgress = useMyTasks({ status: "IN_PROGRESS", size: 1, sort: "updatedAt,desc" });
  const blocked = useMyTasks({ status: "BLOCKED", size: 1, sort: "updatedAt,desc" });
  const count = (data: { pages: { totalElements: number }[] } | undefined) => data?.pages[0]?.totalElements ?? 0;
  return <View style={styles.stack}>
    <WorkflowCard><Text style={[styles.sectionTitle, { color: Colors.textPrimary }]}>{t("taskWorkforce.worker.currentStatus")}</Text>{availability ? <><AvailabilityBadge status={availability.status} /><DetailRow label={t("taskWorkforce.worker.clockedIn")} value={formatTaskDate(availability.clockedInAt, i18n.language)} />{availability.breakStartedAt ? <DetailRow label={t("taskWorkforce.worker.activeBreak")} value={formatTaskDate(availability.breakStartedAt, i18n.language)} /> : null}{availability.unavailabilityReason ? <DetailRow label={t("taskWorkforce.worker.activeOverride")} value={availability.unavailabilityReason} /> : null}{availability.leaveReason ? <DetailRow label={t("taskWorkforce.worker.activeLeave")} value={availability.leaveReason} /> : null}<Text style={{ color: Colors.textSecondary }}>{t(`taskWorkforce.availabilityDescription.${availability.status}`)}</Text></> : <Text style={{ color: Colors.textSecondary }}>{t("taskWorkforce.common.notAvailable")}</Text>}</WorkflowCard>
    <View style={styles.metrics}><Metric label={t("taskWorkforce.worker.availableCount")} value={count(available.data)} onPress={() => onNavigate("available")} /><Metric label={t("taskWorkforce.worker.activeCount")} value={count(assigned.data) + count(inProgress.data)} onPress={() => onNavigate("mine")} /><Metric label={t("taskWorkforce.worker.blockedCount")} value={count(blocked.data)} onPress={() => onNavigate("mine")} /></View>
    <WorkflowCard><Text style={[styles.sectionTitle, { color: Colors.textPrimary }]}>{t("taskWorkforce.worker.attendanceActions")}</Text><AttendanceActions availability={availability} /></WorkflowCard>
  </View>;
}

function Metric({ label, value, onPress }: { label: string; value: number; onPress: () => void }) {
  const { Colors } = useTheme();
  return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={[styles.metric, { backgroundColor: Colors.background, borderColor: Colors.divider }]}><Text style={[styles.metricValue, { color: Colors.primary }]}>{value}</Text><Text style={[styles.metricLabel, { color: Colors.textSecondary }]}>{label}</Text></Pressable>;
}

function AvailableTasks() {
  const { t } = useTranslation(); const { Colors } = useTheme();
  const tasks = useAvailableTasks({ size: 20, sort: "updatedAt,desc" });
  return <View style={styles.stack}><Text style={[styles.sectionTitle, { color: Colors.textPrimary }]}>{t("taskWorkforce.worker.availableTitle")}</Text><Text style={{ color: Colors.textSecondary }}>{t("taskWorkforce.worker.availableHint")}</Text>{tasks.isPending ? <WorkflowState icon="LoaderCircle" title={t("taskWorkforce.common.loading")} description={t("taskWorkforce.worker.loadingTasks")} /> : tasks.isError ? <WorkflowState icon="CircleAlert" title={t("taskWorkforce.common.errorTitle")} description={t("taskWorkforce.worker.availableError")} actionLabel={t("taskWorkforce.common.retry")} onAction={() => void tasks.refetch()} /> : tasks.tasks.length === 0 ? <WorkflowState icon="ClipboardList" title={t("taskWorkforce.worker.availableEmptyTitle")} description={t("taskWorkforce.worker.availableEmptyDescription")} /> : tasks.tasks.map((task) => <WorkerTaskCard key={task.taskId} task={task} />)}<LoadMore visible={Boolean(tasks.hasNextPage)} loading={tasks.isFetchingNextPage} onPress={() => void tasks.fetchNextPage()} /><WorkflowButton label={t("taskWorkforce.common.refresh")} onPress={() => void tasks.refetch()} variant="secondary" icon="RefreshCw" /></View>;
}

function MyTasks() {
  const { t } = useTranslation(); const { Colors } = useTheme();
  const [status, setStatus] = useState<TaskStatus>();
  const filters = useMemo(() => ({ status, size: 20, sort: "updatedAt,desc" }), [status]);
  const tasks = useMyTasks(filters);
  return <View style={styles.stack}><Text style={[styles.sectionTitle, { color: Colors.textPrimary }]}>{t("taskWorkforce.worker.myTitle")}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}><WorkflowChip label={t("taskWorkforce.common.all")} selected={!status} onPress={() => setStatus(undefined)} />{taskStatuses.map((item) => <WorkflowChip key={item} label={t(`taskWorkforce.status.${item}`)} selected={status === item} onPress={() => setStatus(item)} />)}</ScrollView>{tasks.isPending ? <WorkflowState icon="LoaderCircle" title={t("taskWorkforce.common.loading")} description={t("taskWorkforce.worker.loadingTasks")} /> : tasks.isError ? <WorkflowState icon="CircleAlert" title={t("taskWorkforce.common.errorTitle")} description={t("taskWorkforce.worker.mineError")} actionLabel={t("taskWorkforce.common.retry")} onAction={() => void tasks.refetch()} /> : tasks.tasks.length === 0 ? <WorkflowState icon="ClipboardList" title={t("taskWorkforce.worker.mineEmptyTitle")} description={t("taskWorkforce.worker.mineEmptyDescription")} /> : <TaskGroups tasks={tasks.tasks} />}<LoadMore visible={Boolean(tasks.hasNextPage)} loading={tasks.isFetchingNextPage} onPress={() => void tasks.fetchNextPage()} /><WorkflowButton label={t("taskWorkforce.common.refresh")} onPress={() => void tasks.refetch()} variant="secondary" icon="RefreshCw" /></View>;
}

function TaskGroups({ tasks }: { tasks: OperationalTask[] }) {
  const { t } = useTranslation();
  const groups: { name: "active" | "blocked" | "history"; statuses: TaskStatus[] }[] = [{ name: "active", statuses: ["ASSIGNED", "IN_PROGRESS"] }, { name: "blocked", statuses: ["BLOCKED"] }, { name: "history", statuses: ["COMPLETED", "CANCELLED"] }];
  return <View style={styles.stack}>{groups.map((group) => { const items = tasks.filter((task) => group.statuses.includes(task.status)); return items.length ? <View key={group.name} style={styles.stack}><Text style={styles.groupTitle}>{t(`taskWorkforce.worker.groups.${group.name}`)}</Text>{items.map((task) => <WorkerTaskCard key={task.taskId} task={task} />)}</View> : null; })}</View>;
}

function WorkerTaskCard({ task }: { task: OperationalTask }) {
  const { t } = useTranslation(); const { Colors } = useTheme();
  return <Pressable accessibilityRole="button" accessibilityLabel={t("taskWorkforce.worker.openTask", { title: task.title })} onPress={() => router.push({ pathname: "/(worker)/tasks/[id]", params: { id: String(task.taskId) } })} style={[styles.taskCard, { backgroundColor: Colors.background, borderColor: Colors.divider }]}><View style={styles.taskTitleRow}><Text style={[styles.taskTitle, { color: Colors.textPrimary }]}>{task.title}</Text><Text style={{ color: Colors.primary }}>#{task.taskId}</Text></View><View style={styles.badges}><TaskStatusBadge status={task.status} /><PriorityBadge priority={task.priority} /></View><Text style={{ color: Colors.textSecondary }}>{t(`taskWorkforce.specialization.${task.specializationCode}`, { defaultValue: task.specializationCode })}</Text>{task.apartmentId ? <Text style={{ color: Colors.textSecondary }}>{t("taskWorkforce.agent.apartmentValue", { id: task.apartmentId })}</Text> : null}</Pressable>;
}

function Attendance({ availability }: { availability?: WorkerAvailability }) {
  const { t, i18n } = useTranslation(); const { Colors } = useTheme();
  const sessions = useAttendanceHistory({ size: 20, sort: "clockedInAt,desc" });
  return <View style={styles.stack}><WorkflowCard><Text style={[styles.sectionTitle, { color: Colors.textPrimary }]}>{t("taskWorkforce.worker.attendanceActions")}</Text><AttendanceActions availability={availability} /></WorkflowCard><Text style={[styles.sectionTitle, { color: Colors.textPrimary }]}>{t("taskWorkforce.worker.attendanceHistory")}</Text>{sessions.isPending ? <WorkflowState icon="LoaderCircle" title={t("taskWorkforce.common.loading")} description={t("taskWorkforce.worker.loadingAttendance")} /> : sessions.isError ? <WorkflowState icon="CircleAlert" title={t("taskWorkforce.common.errorTitle")} description={t("taskWorkforce.worker.attendanceError")} actionLabel={t("taskWorkforce.common.retry")} onAction={() => void sessions.refetch()} /> : sessions.rows.length === 0 ? <WorkflowState icon="ClipboardList" title={t("taskWorkforce.worker.attendanceEmptyTitle")} description={t("taskWorkforce.worker.attendanceEmptyDescription")} /> : sessions.rows.map((session) => <AttendanceCard key={session.attendanceSessionId} session={session} locale={i18n.language} />)}<LoadMore visible={Boolean(sessions.hasNextPage)} loading={sessions.isFetchingNextPage} onPress={() => void sessions.fetchNextPage()} /></View>;
}

function AttendanceActions({ availability }: { availability?: WorkerAvailability }) {
  const { t } = useTranslation(); const { Colors } = useTheme();
  const inMutation = useClockIn(); const startBreak = useStartBreak(); const endBreak = useEndBreak(); const outMutation = useClockOut();
  const [outConfirm, setOutConfirm] = useState(false); const [error, setError] = useState("");
  const run = (mutation: { mutate: (value: void, options: { onError: (error: unknown) => void }) => void }) => mutation.mutate(undefined, { onError: (requestError) => setError(getUserFacingErrorMessage(requestError, t("taskWorkforce.worker.attendanceActionError"))) });
  if (!availability) { return null; }
  return <View style={styles.stack}>{error ? <Text style={{ color: Colors.error }}>{error}</Text> : null}{!availability.attendanceSessionId ? <WorkflowButton label={t("taskWorkforce.worker.clockIn")} onPress={() => run(inMutation)} loading={inMutation.isPending} icon="Clock" /> : null}{availability.attendanceSessionId && !availability.breakStartedAt ? <WorkflowButton label={t("taskWorkforce.worker.startBreak")} onPress={() => run(startBreak)} loading={startBreak.isPending} variant="secondary" /> : null}{availability.breakStartedAt ? <WorkflowButton label={t("taskWorkforce.worker.endBreak")} onPress={() => run(endBreak)} loading={endBreak.isPending} /> : null}{availability.attendanceSessionId && !availability.breakStartedAt ? <WorkflowButton label={t("taskWorkforce.worker.clockOut")} onPress={() => setOutConfirm(true)} loading={outMutation.isPending} variant="danger" /> : null}<SimpleConfirmation visible={outConfirm} title={t("taskWorkforce.worker.clockOutTitle")} description={t("taskWorkforce.worker.clockOutDescription")} confirmLabel={t("taskWorkforce.worker.confirmClockOut")} confirming={outMutation.isPending} onClose={() => !outMutation.isPending && setOutConfirm(false)} onConfirm={() => outMutation.mutate(undefined, { onSuccess: () => setOutConfirm(false), onError: (requestError) => setError(getUserFacingErrorMessage(requestError, t("taskWorkforce.worker.attendanceActionError"))) })} /></View>;
}

function AttendanceCard({ session, locale }: { session: AttendanceSession; locale: string }) {
  const { t } = useTranslation(); const { Colors } = useTheme();
  return <WorkflowCard><DetailRow label={t("taskWorkforce.worker.clockedIn")} value={formatTaskDate(session.clockedInAt, locale)} /><DetailRow label={t("taskWorkforce.worker.clockedOut")} value={formatTaskDate(session.clockedOutAt, locale)} /><Text style={[styles.subTitle, { color: Colors.textPrimary }]}>{t("taskWorkforce.worker.breaks")}</Text>{session.breaks.length ? session.breaks.map((period) => <DetailRow key={period.breakPeriodId} label={formatTaskDate(period.startedAt, locale)} value={formatTaskDate(period.endedAt, locale)} />) : <Text style={{ color: Colors.textSecondary }}>{t("taskWorkforce.worker.noBreaks")}</Text>}</WorkflowCard>;
}

function Overrides() {
  const { t, i18n } = useTranslation(); const { Colors } = useTheme();
  const [startsAt, setStartsAt] = useState<Date>(); const [endsAt, setEndsAt] = useState<Date>(); const [reason, setReason] = useState(""); const [picker, setPicker] = useState<"start" | "end">(); const [formError, setFormError] = useState("");
  const overrides = useAvailabilityOverrides({ size: 20, sort: "startsAt,desc" }); const create = useCreateAvailabilityOverride(); const clear = useClearAvailabilityOverride();
  const submit = () => { const cleaned = reason.trim(); const begin = startsAt ?? new Date(); if (!cleaned || cleaned.length > 300) { setFormError(t("taskWorkforce.worker.overrideReasonValidation")); return; } if (endsAt && endsAt <= begin) { setFormError(t("taskWorkforce.worker.periodValidation")); return; } create.mutate({ ...(startsAt ? { startsAt: startsAt.toISOString() } : {}), ...(endsAt ? { endsAt: endsAt.toISOString() } : {}), reason: cleaned }, { onSuccess: () => { setReason(""); setStartsAt(undefined); setEndsAt(undefined); setFormError(""); }, onError: (requestError) => setFormError(getUserFacingErrorMessage(requestError, t("taskWorkforce.worker.overrideError"))) }); };
  return <View style={styles.stack}><WorkflowCard><Text style={[styles.sectionTitle, { color: Colors.textPrimary }]}>{t("taskWorkforce.worker.overrideTitle")}</Text><Text style={{ color: Colors.textSecondary }}>{t("taskWorkforce.worker.overrideHint")}</Text><InstantField label={t("taskWorkforce.worker.startsAtOptional")} value={startsAt} locale={i18n.language} onPress={() => setPicker("start")} onClear={() => setStartsAt(undefined)} /><InstantField label={t("taskWorkforce.worker.endsAtOptional")} value={endsAt} locale={i18n.language} onPress={() => setPicker("end")} onClear={() => setEndsAt(undefined)} /><TextInput accessibilityLabel={t("taskWorkforce.worker.reason")} value={reason} onChangeText={setReason} maxLength={300} multiline textAlignVertical="top" placeholder={t("taskWorkforce.worker.reason")} placeholderTextColor={Colors.tertiary} style={[styles.reasonInput, { color: Colors.textPrimary, backgroundColor: Colors.screenBackground, borderColor: Colors.divider }]} /><Text style={{ color: Colors.textSecondary }}>{reason.length}/300</Text>{formError ? <Text style={{ color: Colors.error }}>{formError}</Text> : null}<WorkflowButton label={t("taskWorkforce.worker.submitOverride")} onPress={submit} loading={create.isPending} /></WorkflowCard><Text style={[styles.sectionTitle, { color: Colors.textPrimary }]}>{t("taskWorkforce.worker.overrideHistory")}</Text>{overrides.isPending ? <WorkflowState icon="LoaderCircle" title={t("taskWorkforce.common.loading")} description={t("taskWorkforce.worker.loadingOverrides")} /> : overrides.isError ? <WorkflowState icon="CircleAlert" title={t("taskWorkforce.common.errorTitle")} description={t("taskWorkforce.worker.overrideLoadError")} actionLabel={t("taskWorkforce.common.retry")} onAction={() => void overrides.refetch()} /> : overrides.rows.length === 0 ? <WorkflowState icon="ClipboardList" title={t("taskWorkforce.worker.overrideEmptyTitle")} description={t("taskWorkforce.worker.overrideEmptyDescription")} /> : overrides.rows.map((override) => <OverrideCard key={override.availabilityOverrideId} item={override} locale={i18n.language} onClear={() => clear.mutate(override.availabilityOverrideId)} clearing={clear.isPending} />)}<LoadMore visible={Boolean(overrides.hasNextPage)} loading={overrides.isFetchingNextPage} onPress={() => void overrides.fetchNextPage()} /><DateTimePicker visible={picker !== undefined} initialValue={picker === "start" ? startsAt ?? null : endsAt ?? null} onClose={() => setPicker(undefined)} onConfirm={(value) => picker === "start" ? setStartsAt(value) : setEndsAt(value)} /></View>;
}

function OverrideCard({ item, locale, onClear, clearing }: { item: AvailabilityOverride; locale: string; onClear: () => void; clearing: boolean }) {
  const { t } = useTranslation(); const { Colors } = useTheme();
  return <WorkflowCard><DetailRow label={t("taskWorkforce.worker.startsAt")} value={formatTaskDate(item.startsAt, locale)} /><DetailRow label={t("taskWorkforce.worker.endsAt")} value={formatTaskDate(item.endsAt, locale)} /><Text style={{ color: Colors.textPrimary }}>{item.reason}</Text>{item.clearedAt ? <DetailRow label={t("taskWorkforce.worker.clearedAt")} value={formatTaskDate(item.clearedAt, locale)} /> : <WorkflowButton label={t("taskWorkforce.worker.clearOverride")} onPress={onClear} loading={clearing} variant="secondary" />}</WorkflowCard>;
}

function LeaveRequests() {
  const { t, i18n } = useTranslation(); const { Colors } = useTheme();
  const [startsAt, setStartsAt] = useState<Date>(); const [endsAt, setEndsAt] = useState<Date>(); const [reason, setReason] = useState(""); const [picker, setPicker] = useState<"start" | "end">(); const [formError, setFormError] = useState("");
  const leaves = useLeaveRequests({ size: 20, sort: "createdAt,desc" }); const create = useCreateLeaveRequest(); const cancel = useCancelLeaveRequest();
  const submit = () => { const cleaned = reason.trim(); if (!startsAt || !endsAt || endsAt <= startsAt) { setFormError(t("taskWorkforce.worker.leavePeriodValidation")); return; } if (!cleaned || cleaned.length > 300) { setFormError(t("taskWorkforce.worker.leaveReasonValidation")); return; } create.mutate({ startsAt: startsAt.toISOString(), endsAt: endsAt.toISOString(), reason: cleaned }, { onSuccess: () => { setStartsAt(undefined); setEndsAt(undefined); setReason(""); setFormError(""); }, onError: (requestError) => setFormError(getUserFacingErrorMessage(requestError, t("taskWorkforce.worker.leaveError"))) }); };
  return <View style={styles.stack}><WorkflowCard><Text style={[styles.sectionTitle, { color: Colors.textPrimary }]}>{t("taskWorkforce.worker.leaveTitle")}</Text><Text style={{ color: Colors.textSecondary }}>{t("taskWorkforce.worker.leaveHint")}</Text><InstantField label={t("taskWorkforce.worker.startsAt")} value={startsAt} locale={i18n.language} onPress={() => setPicker("start")} /><InstantField label={t("taskWorkforce.worker.endsAt")} value={endsAt} locale={i18n.language} onPress={() => setPicker("end")} /><TextInput accessibilityLabel={t("taskWorkforce.worker.reason")} value={reason} onChangeText={setReason} maxLength={300} multiline textAlignVertical="top" placeholder={t("taskWorkforce.worker.reason")} placeholderTextColor={Colors.tertiary} style={[styles.reasonInput, { color: Colors.textPrimary, backgroundColor: Colors.screenBackground, borderColor: Colors.divider }]} /><Text style={{ color: Colors.textSecondary }}>{reason.length}/300</Text>{formError ? <Text style={{ color: Colors.error }}>{formError}</Text> : null}<WorkflowButton label={t("taskWorkforce.worker.submitLeave")} onPress={submit} loading={create.isPending} /></WorkflowCard><Text style={[styles.sectionTitle, { color: Colors.textPrimary }]}>{t("taskWorkforce.worker.leaveHistory")}</Text>{leaves.isPending ? <WorkflowState icon="LoaderCircle" title={t("taskWorkforce.common.loading")} description={t("taskWorkforce.worker.loadingLeave")} /> : leaves.isError ? <WorkflowState icon="CircleAlert" title={t("taskWorkforce.common.errorTitle")} description={t("taskWorkforce.worker.leaveLoadError")} actionLabel={t("taskWorkforce.common.retry")} onAction={() => void leaves.refetch()} /> : leaves.rows.length === 0 ? <WorkflowState icon="ClipboardList" title={t("taskWorkforce.worker.leaveEmptyTitle")} description={t("taskWorkforce.worker.leaveEmptyDescription")} /> : leaves.rows.map((leave) => <LeaveCard key={leave.leaveRequestId} item={leave} locale={i18n.language} onCancel={() => cancel.mutate(leave.leaveRequestId)} cancelling={cancel.isPending} />)}<LoadMore visible={Boolean(leaves.hasNextPage)} loading={leaves.isFetchingNextPage} onPress={() => void leaves.fetchNextPage()} /><DateTimePicker visible={picker !== undefined} initialValue={picker === "start" ? startsAt ?? null : endsAt ?? null} onClose={() => setPicker(undefined)} onConfirm={(value) => picker === "start" ? setStartsAt(value) : setEndsAt(value)} /></View>;
}

function LeaveCard({ item, locale, onCancel, cancelling }: { item: LeaveRequest; locale: string; onCancel: () => void; cancelling: boolean }) {
  const { t } = useTranslation(); const { Colors } = useTheme(); const canCancel = item.status === "PENDING" || item.status === "APPROVED";
  return <WorkflowCard><Text style={[styles.leaveStatus, { color: Colors.primary }]}>{t(`taskWorkforce.leaveStatus.${item.status}`)}</Text><DetailRow label={t("taskWorkforce.worker.startsAt")} value={formatTaskDate(item.startsAt, locale)} /><DetailRow label={t("taskWorkforce.worker.endsAt")} value={formatTaskDate(item.endsAt, locale)} /><Text style={{ color: Colors.textPrimary }}>{item.reason}</Text>{item.decisionReason ? <DetailRow label={t("taskWorkforce.worker.decisionReason")} value={item.decisionReason} /> : null}{item.decidedAt ? <DetailRow label={t("taskWorkforce.worker.decidedAt")} value={formatTaskDate(item.decidedAt, locale)} /> : null}{canCancel ? <WorkflowButton label={t("taskWorkforce.worker.cancelLeave")} onPress={onCancel} loading={cancelling} variant="secondary" /> : null}</WorkflowCard>;
}

function InstantField({ label, value, locale, onPress, onClear }: { label: string; value?: Date; locale: string; onPress: () => void; onClear?: () => void }) {
  const { t } = useTranslation(); const { Colors } = useTheme();
  return <View style={styles.instantField}><Text style={{ color: Colors.textSecondary, fontWeight: "700" }}>{label}</Text><View style={styles.instantActions}><View style={styles.instantButton}><WorkflowButton label={value ? formatTaskDate(value.toISOString(), locale) : t("taskWorkforce.worker.chooseInstant")} onPress={onPress} variant="secondary" /></View>{onClear && value ? <Pressable accessibilityRole="button" accessibilityLabel={t("taskWorkforce.common.clear")} onPress={onClear}><Text style={{ color: Colors.primary, fontWeight: "800" }}>{t("taskWorkforce.common.clear")}</Text></Pressable> : null}</View></View>;
}

function SimpleConfirmation({ visible, title, description, confirmLabel, confirming, onClose, onConfirm }: { visible: boolean; title: string; description: string; confirmLabel: string; confirming: boolean; onClose: () => void; onConfirm: () => void }) {
  const { t } = useTranslation(); const { Colors } = useTheme();
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={styles.modalOverlay}><View style={[styles.modalCard, { backgroundColor: Colors.background }]}><Text style={[styles.modalTitle, { color: Colors.textPrimary }]}>{title}</Text><Text style={{ color: Colors.textSecondary }}>{description}</Text><View style={styles.modalActions}><View style={styles.flex}><WorkflowButton label={t("taskWorkforce.common.close")} onPress={onClose} variant="secondary" disabled={confirming} /></View><View style={styles.flex}><WorkflowButton label={confirmLabel} onPress={onConfirm} loading={confirming} /></View></View></View></View></Modal>;
}

const styles = StyleSheet.create({ screen: { flex: 1 }, content: { padding: 16, paddingBottom: 32, gap: 14 }, heading: { gap: 5 }, title: { fontSize: 24, fontWeight: "800" }, sectionTitle: { fontSize: 17, fontWeight: "800" }, subTitle: { fontSize: 14, fontWeight: "800" }, groupTitle: { fontSize: 15, fontWeight: "800" }, leaveStatus: { alignSelf: "flex-start", fontSize: 12, fontWeight: "800" }, stack: { gap: 10 }, chips: { gap: 8, paddingRight: 4 }, metrics: { flexDirection: "row", gap: 8 }, metric: { flex: 1, minHeight: 92, borderWidth: 1, borderRadius: 14, padding: 10, justifyContent: "space-between" }, metricValue: { fontSize: 26, fontWeight: "800" }, metricLabel: { fontSize: 12, fontWeight: "700" }, taskCard: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 8 }, taskTitleRow: { flexDirection: "row", gap: 12, justifyContent: "space-between" }, taskTitle: { flex: 1, fontSize: 16, fontWeight: "800" }, badges: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, reasonInput: { minHeight: 96, borderWidth: 1, borderRadius: 12, padding: 11 }, instantField: { gap: 6 }, instantActions: { flexDirection: "row", gap: 8, alignItems: "center" }, instantButton: { flex: 1 }, modalOverlay: { flex: 1, padding: 20, justifyContent: "center", backgroundColor: "rgba(0,0,0,0.45)" }, modalCard: { borderRadius: 16, padding: 18, gap: 12 }, modalTitle: { fontSize: 20, fontWeight: "800" }, modalActions: { flexDirection: "row", gap: 10 }, flex: { flex: 1 } });
