package org.unibl.etf.blueStars.repositories;
import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.test.context.bean.override.mockito.MockitoBean; import org.springframework.transaction.support.TransactionTemplate; import org.unibl.etf.blueStars.models.entities.AppUser; import org.unibl.etf.blueStars.models.enums.*; import org.unibl.etf.blueStars.models.requests.CreateTaskRequest; import org.unibl.etf.blueStars.services.*; import org.unibl.etf.blueStars.services.interfaces.S3Service; import java.util.*; import java.util.concurrent.*; import static org.assertj.core.api.Assertions.assertThat;
@SpringBootTest class B09TaskClaimConcurrencyIntegrationTest {
 @Autowired TransactionTemplate tx; @Autowired AppUserRepository users; @Autowired SpecializationRepository specializations; @Autowired TaskService tasks; @Autowired WorkforceAvailabilityService workforce; @MockitoBean S3Service storage;
 @Test void onlyOneConcurrentWorkerClaimsTheSameTask() throws Exception {
  Object[] setup=tx.execute(x->{var spec=specializations.findAll().stream().filter(s->s.getCode().equals("INSPECTION")).findFirst().orElseThrow();AppUser manager=save("manager",UserRole.MANAGER);AppUser a=save("a",UserRole.OPERATIONAL_WORKER);AppUser b=save("b",UserRole.OPERATIONAL_WORKER);a.getSpecializations().add(spec);b.getSpecializations().add(spec);users.saveAllAndFlush(List.of(a,b));workforce.clockIn(a.getEmail());workforce.clockIn(b.getEmail());Long id=tasks.create(manager.getEmail(),new CreateTaskRequest(spec.getSpecializationId(),null,null,"Inspect room","Routine inspection",TaskPriority.NORMAL)).taskId();return new Object[]{id,a.getEmail(),b.getEmail()};});
  Long id=(Long)setup[0];CountDownLatch ready=new CountDownLatch(2),start=new CountDownLatch(1);var pool=Executors.newFixedThreadPool(2);
  try{var f1=pool.submit(()->claim((String)setup[1],id,ready,start));var f2=pool.submit(()->claim((String)setup[2],id,ready,start));ready.await();start.countDown();assertThat(List.of(f1.get(),f2.get())).containsExactlyInAnyOrder(true,false);}finally{pool.shutdownNow();}
 }
 private boolean claim(String email,Long id,CountDownLatch ready,CountDownLatch start){ready.countDown();try{start.await();tasks.claim(email,id);return true;}catch(RuntimeException e){return false;}catch(InterruptedException e){Thread.currentThread().interrupt();throw new IllegalStateException(e);}}
 private AppUser save(String label,UserRole role){String s=UUID.randomUUID().toString().replace("-","").substring(0,12);AppUser u=new AppUser();u.setName("B09");u.setSurname(label);u.setJmbg(String.format("%013d",Integer.toUnsignedLong(s.hashCode())%10_000_000_000_000L));u.setPasswordHash("hash");u.setEmail("b09c-"+label+"-"+s+"@example.invalid");u.setRole(role);u.setAddress("Concurrency address");u.setActive(true);return users.saveAndFlush(u);}
}
