import { formatMoney, isOptionalPositiveMoney, normalizeMoneyInput } from "@/src/components/screens/ExpenseWorkflowScreen/expenseWorkflowHelpers";
import { WorkflowButton, WorkflowCard } from "@/src/components/screens/TaskWorkflowScreen/TaskWorkflowUi";
import { useCreateDamage } from "@/src/hooks/useDamages";
import { useTheme } from "@/src/providers/ThemeProvider";
import { getUserFacingErrorMessage } from "@/src/util/apiError";
import { InvalidRouteState } from "@/src/components/screens/InvalidRouteState";
import { parsePositiveId } from "@/src/util/idParams";
import { router, useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { useTranslation } from "react-i18next";
import { Modal, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

export default function DamageCreateScreen() {
  const { t } = useTranslation(); const { Colors } = useTheme(); const { apartmentId: rawApartmentId } = useLocalSearchParams<{ apartmentId?: string | string[] }>(); const apartmentId = parsePositiveId(rawApartmentId);
  const create = useCreateDamage(); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [estimatedAmount, setEstimatedAmount] = useState(""); const [confirmedAmount, setConfirmedAmount] = useState(""); const [validationError, setValidationError] = useState(""); const [requestError, setRequestError] = useState(""); const [confirming, setConfirming] = useState(false);
  const prepare = () => {
    const cleanedTitle = title.trim(); const cleanedDescription = description.trim(); const estimated = normalizeMoneyInput(estimatedAmount); const confirmed = normalizeMoneyInput(confirmedAmount);
    if (!cleanedTitle || cleanedTitle.length > 120) setValidationError(t("damageWorkflow.validation.title"));
    else if (!cleanedDescription || cleanedDescription.length > 2000) setValidationError(t("damageWorkflow.validation.description"));
    else if (!isOptionalPositiveMoney(estimated) || !isOptionalPositiveMoney(confirmed)) setValidationError(t("damageWorkflow.validation.amount"));
    else { setValidationError(""); setRequestError(""); setConfirming(true); }
  };
  const submit = () => create.mutate({ apartmentId, request: { title: title.trim(), description: description.trim(), estimatedAmount: normalizeMoneyInput(estimatedAmount) || null, confirmedAmount: normalizeMoneyInput(confirmedAmount) || null } }, { onSuccess: (damage) => { setConfirming(false); router.replace({ pathname: "/(home)/damages/[id]", params: { id: String(damage.damageId), apartmentId: String(apartmentId) } }); }, onError: (error) => setRequestError(getUserFacingErrorMessage(error, t("damageWorkflow.create.submitError"))) });
  if (apartmentId === null) return <InvalidRouteState fallbackHref="/(home)/damages" />;
  return <SafeAreaView edges={["bottom"]} style={[styles.screen, { backgroundColor: Colors.screenBackground }]}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={[styles.title, { color: Colors.textPrimary }]}>{t("damageWorkflow.create.title")}</Text><Text style={{ color: Colors.textSecondary }}>{t("damageWorkflow.create.hint", { id: apartmentId })}</Text><WorkflowCard><Field label={t("damageWorkflow.create.titleLabel")} value={title} onChangeText={setTitle} maxLength={120} placeholder={t("damageWorkflow.create.titlePlaceholder")} /><Field label={t("damageWorkflow.create.description")} value={description} onChangeText={setDescription} maxLength={2000} placeholder={t("damageWorkflow.create.descriptionPlaceholder")} multiline /><Field label={t("damageWorkflow.create.estimated")} value={estimatedAmount} onChangeText={setEstimatedAmount} placeholder="0.00" keyboardType="decimal-pad" /><Field label={t("damageWorkflow.create.confirmed")} value={confirmedAmount} onChangeText={setConfirmedAmount} placeholder="0.00" keyboardType="decimal-pad" />{validationError ? <Text style={{ color: Colors.error }}>{validationError}</Text> : null}{requestError ? <Text style={{ color: Colors.error }}>{requestError}</Text> : null}<WorkflowButton label={t("damageWorkflow.create.review")} onPress={prepare} icon="ChevronRight" /></WorkflowCard><Confirmation visible={confirming} submitting={create.isPending} title={title.trim()} description={description.trim()} estimated={normalizeMoneyInput(estimatedAmount)} confirmed={normalizeMoneyInput(confirmedAmount)} error={requestError} onClose={() => !create.isPending && setConfirming(false)} onConfirm={submit} /></ScrollView></SafeAreaView>;
}

function Field({ label, value, onChangeText, maxLength, placeholder, multiline = false, keyboardType }: { label: string; value: string; onChangeText: (value: string) => void; maxLength?: number; placeholder: string; multiline?: boolean; keyboardType?: "decimal-pad" }) { const { Colors } = useTheme(); return <View style={styles.field}><Text style={[styles.label, { color: Colors.textPrimary }]}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChangeText} maxLength={maxLength} multiline={multiline} keyboardType={keyboardType} placeholder={placeholder} placeholderTextColor={Colors.textSecondary} textAlignVertical={multiline ? "top" : "center"} style={[styles.input, multiline && styles.multiline, { color: Colors.textPrimary, borderColor: Colors.divider, backgroundColor: Colors.screenBackground }]} /></View>; }
function Confirmation({ visible, submitting, title, description, estimated, confirmed, error, onClose, onConfirm }: { visible: boolean; submitting: boolean; title: string; description: string; estimated: string; confirmed: string; error: string; onClose: () => void; onConfirm: () => void }) { const { t } = useTranslation(); const { Colors } = useTheme(); return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={styles.overlay}><View style={[styles.modal, { backgroundColor: Colors.background }]}><Text style={[styles.modalTitle, { color: Colors.textPrimary }]}>{t("damageWorkflow.create.confirmTitle")}</Text><Text style={{ color: Colors.textPrimary, fontWeight: "800" }}>{title}</Text><Text style={{ color: Colors.textSecondary }}>{description}</Text><Text style={{ color: Colors.textPrimary }}>{t("damageWorkflow.create.estimated")}: {formatMoney(estimated || null, t("damageWorkflow.common.currency"))}</Text><Text style={{ color: Colors.textPrimary }}>{t("damageWorkflow.create.confirmed")}: {formatMoney(confirmed || null, t("damageWorkflow.common.currency"))}</Text>{error ? <Text style={{ color: Colors.error }}>{error}</Text> : null}<View style={styles.actions}><View style={styles.flex}><WorkflowButton label={t("damageWorkflow.common.cancel")} onPress={onClose} variant="secondary" disabled={submitting} /></View><View style={styles.flex}><WorkflowButton label={t("damageWorkflow.create.submit")} onPress={onConfirm} loading={submitting} /></View></View></View></View></Modal>; }
const styles = StyleSheet.create({ screen: { flex: 1, padding: 16 }, content: { gap: 12, paddingBottom: 32 }, title: { fontSize: 24, fontWeight: "800" }, field: { gap: 6 }, label: { fontSize: 14, fontWeight: "800" }, input: { minHeight: 46, borderWidth: 1, borderRadius: 12, paddingHorizontal: 12, fontSize: 16 }, multiline: { minHeight: 120, paddingTop: 10 }, overlay: { flex: 1, justifyContent: "center", padding: 20, backgroundColor: "rgba(0,0,0,0.45)" }, modal: { padding: 18, borderRadius: 16, gap: 11 }, modalTitle: { fontSize: 20, fontWeight: "800" }, actions: { flexDirection: "row", gap: 10 }, flex: { flex: 1 } });
