import * as DocumentPicker from "expo-document-picker";
import * as WebBrowser from "expo-web-browser";
import { formatFileSize, formatMoney, formatTimestamp } from "@/src/components/screens/ExpenseWorkflowScreen/expenseWorkflowHelpers";
import { DetailRow, WorkflowButton, WorkflowCard, WorkflowState } from "@/src/components/screens/TaskWorkflowScreen/TaskWorkflowUi";
import { useDamageAttachments, useDamageDetail, useUploadDamageAttachment } from "@/src/hooks/useDamages";
import { useTaskDetail } from "@/src/hooks/useTaskWorkflows";
import { useTheme } from "@/src/providers/ThemeProvider";
import { getUserFacingErrorMessage } from "@/src/util/apiError";
import { useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { isAxiosError } from "axios";

const activeWorkerStatuses = ["ASSIGNED", "IN_PROGRESS", "BLOCKED"] as const;
const MAX_ATTACHMENT_SIZE = 10 * 1024 * 1024;

export default function DamageDetailScreen({ workerTaskId }: { workerTaskId?: number } = {}) {
  const { t, i18n } = useTranslation(); const { Colors } = useTheme(); const params = useLocalSearchParams<{ id?: string; apartmentId?: string; damageId?: string }>();
  const apartmentId = Number(params.apartmentId); const damageId = Number(params.damageId ?? params.id); const isWorkerRoute = workerTaskId !== undefined;
  const task = useTaskDetail(workerTaskId ?? 0);
  const taskAllowsAccess = !isWorkerRoute || Boolean(task.data?.apartmentId === apartmentId && task.data.assignedWorkerId !== null && activeWorkerStatuses.includes(task.data.status as typeof activeWorkerStatuses[number]));
  const damage = useDamageDetail(apartmentId, damageId, taskAllowsAccess);
  const attachments = useDamageAttachments(apartmentId, damageId, taskAllowsAccess);
  const accessRequestFailed = isAxiosError(damage.error) && (damage.error.response?.status === 403 || damage.error.response?.status === 404);

  useEffect(() => {
    if (!isWorkerRoute || !workerTaskId || !Number.isInteger(workerTaskId)) return;
    const timer = setInterval(() => void task.refetch(), 20_000);
    return () => clearInterval(timer);
  }, [isWorkerRoute, task, workerTaskId]);

  if (!Number.isInteger(apartmentId) || apartmentId <= 0 || !Number.isInteger(damageId) || damageId <= 0) return <SafeAreaView style={[styles.screen, { backgroundColor: Colors.screenBackground }]}><WorkflowState icon="CircleAlert" title={t("damageWorkflow.common.errorTitle")} description={t("damageWorkflow.detail.invalid")} /></SafeAreaView>;
  if (isWorkerRoute && task.isPending) return <SafeAreaView style={[styles.screen, { backgroundColor: Colors.screenBackground }]}><WorkflowState icon="LoaderCircle" title={t("damageWorkflow.common.loading")} description={t("damageWorkflow.worker.checkingAccess")} /></SafeAreaView>;
  if (isWorkerRoute && (task.isError || !taskAllowsAccess)) return <SafeAreaView style={[styles.screen, { backgroundColor: Colors.screenBackground }]}><WorkflowState icon="CircleAlert" title={t("damageWorkflow.worker.accessLostTitle")} description={t("damageWorkflow.worker.accessLost")} actionLabel={t("damageWorkflow.common.retry")} onAction={() => void task.refetch()} /></SafeAreaView>;
  if (damage.isPending) return <SafeAreaView style={[styles.screen, { backgroundColor: Colors.screenBackground }]}><WorkflowState icon="LoaderCircle" title={t("damageWorkflow.common.loading")} description={t("damageWorkflow.detail.loading")} /></SafeAreaView>;
  if (isWorkerRoute && accessRequestFailed) return <SafeAreaView style={[styles.screen, { backgroundColor: Colors.screenBackground }]}><WorkflowState icon="CircleAlert" title={t("damageWorkflow.worker.accessLostTitle")} description={t("damageWorkflow.worker.accessLost")} actionLabel={t("damageWorkflow.common.retry")} onAction={() => void task.refetch()} /></SafeAreaView>;
  if (damage.isError || !damage.data) return <SafeAreaView style={[styles.screen, { backgroundColor: Colors.screenBackground }]}><WorkflowState icon="CircleAlert" title={t("damageWorkflow.common.errorTitle")} description={t("damageWorkflow.detail.loadError")} actionLabel={t("damageWorkflow.common.retry")} onAction={() => void Promise.all([damage.refetch(), isWorkerRoute ? task.refetch() : Promise.resolve()])} /></SafeAreaView>;
  const data = damage.data; const author = [data.authorName, data.authorSurname].filter(Boolean).join(" ") || `#${data.createdBy}`;
  return <SafeAreaView edges={["bottom"]} style={[styles.screen, { backgroundColor: Colors.screenBackground }]}><ScrollView contentContainerStyle={styles.content}><View style={styles.titleRow}><Text style={[styles.title, { color: Colors.textPrimary }]}>{data.title}</Text><WorkflowButton label={t("damageWorkflow.common.refresh")} onPress={() => void Promise.all([damage.refetch(), attachments.refetch(), isWorkerRoute ? task.refetch() : Promise.resolve()])} variant="secondary" icon="RefreshCw" /></View><WorkflowCard><DetailRow label={t("damageWorkflow.detail.apartment")} value={`#${data.apartmentId}`} /><DetailRow label={t("damageWorkflow.detail.estimated")} value={formatMoney(data.estimatedAmount, t("damageWorkflow.common.currency"))} /><DetailRow label={t("damageWorkflow.detail.confirmed")} value={formatMoney(data.confirmedAmount, t("damageWorkflow.common.currency"))} /><DetailRow label={t("damageWorkflow.detail.author")} value={author} /><DetailRow label={t("damageWorkflow.detail.createdAt")} value={formatTimestamp(data.createdAt, i18n.language)} /><DetailRow label={t("damageWorkflow.detail.updatedBy")} value={data.updatedBy ? `#${data.updatedBy}` : "—"} /><DetailRow label={t("damageWorkflow.detail.updatedAt")} value={formatTimestamp(data.updatedAt, i18n.language)} /><Text style={[styles.label, { color: Colors.textSecondary }]}>{t("damageWorkflow.detail.description")}</Text><Text style={{ color: Colors.textPrimary }}>{data.description}</Text></WorkflowCard><DamageAttachments apartmentId={apartmentId} damageId={damageId} attachments={attachments.data ?? []} loading={attachments.isPending} error={attachments.isError} canUpload={taskAllowsAccess} locale={i18n.language} onRefresh={() => void attachments.refetch()} /></ScrollView></SafeAreaView>;
}

export function DamageAttachments({ apartmentId, damageId, attachments, loading, error, canUpload, locale, onRefresh }: { apartmentId: number; damageId: number; attachments: { damageAttachmentId: number; originalName: string; contentType: string | null; sizeBytes: number; uploadedBy: number; uploadedAt: string; downloadUrl: string }[]; loading: boolean; error: boolean; canUpload: boolean; locale: string; onRefresh: () => void }) {
  const { t } = useTranslation(); const { Colors } = useTheme(); const upload = useUploadDamageAttachment(); const [uploadError, setUploadError] = useState("");
  const pick = async () => { const result = await DocumentPicker.getDocumentAsync({ type: "*/*", copyToCacheDirectory: true, multiple: false }); if (result.canceled) return; const file = result.assets[0]; if (!file || (file.size !== undefined && (file.size < 1 || file.size > MAX_ATTACHMENT_SIZE))) { setUploadError(t("damageWorkflow.attachments.sizeError")); return; } upload.mutate({ apartmentId, damageId, file: { uri: file.uri, name: file.name, mimeType: file.mimeType, ...(file.file ? { file: file.file } : {}) } }, { onSuccess: () => { setUploadError(""); onRefresh(); }, onError: (requestError) => setUploadError(getUserFacingErrorMessage(requestError, t("damageWorkflow.attachments.uploadError"))) }); };
  return <WorkflowCard><View style={styles.sectionHeader}><Text style={[styles.sectionTitle, { color: Colors.textPrimary }]}>{t("damageWorkflow.attachments.title")}</Text><WorkflowButton label={t("damageWorkflow.common.refresh")} onPress={onRefresh} variant="secondary" icon="RefreshCw" /></View>{uploadError ? <Text style={{ color: Colors.error }}>{uploadError}</Text> : null}{canUpload ? <><Text style={{ color: Colors.textSecondary }}>{t("damageWorkflow.attachments.limit")}</Text><WorkflowButton label={t("damageWorkflow.attachments.add")} onPress={() => void pick()} loading={upload.isPending} icon="Upload" /></> : <Text style={{ color: Colors.textSecondary }}>{t("damageWorkflow.worker.noUpload")}</Text>}{loading ? <ActivityIndicator color={Colors.primary} /> : error ? <WorkflowState icon="CircleAlert" title={t("damageWorkflow.common.errorTitle")} description={t("damageWorkflow.attachments.loadError")} actionLabel={t("damageWorkflow.common.retry")} onAction={onRefresh} /> : attachments.length === 0 ? <Text style={{ color: Colors.textSecondary }}>{t("damageWorkflow.attachments.empty")}</Text> : attachments.map((attachment) => <Attachment key={attachment.damageAttachmentId} attachment={attachment} locale={locale} onRefresh={onRefresh} />)}</WorkflowCard>;
}

function Attachment({ attachment, locale, onRefresh }: { attachment: { originalName: string; contentType: string | null; sizeBytes: number; uploadedBy: number; uploadedAt: string; downloadUrl: string }; locale: string; onRefresh: () => void }) { const { t } = useTranslation(); const { Colors } = useTheme(); const [opening, setOpening] = useState(false); const [openError, setOpenError] = useState(""); const open = async () => { setOpening(true); setOpenError(""); try { await WebBrowser.openBrowserAsync(attachment.downloadUrl); } catch { setOpenError(t("damageWorkflow.attachments.downloadError")); onRefresh(); } finally { setOpening(false); } }; return <View style={[styles.attachment, { borderTopColor: Colors.divider }]}><Text style={{ color: Colors.textPrimary, fontWeight: "800" }}>{attachment.originalName}</Text><Text style={{ color: Colors.textSecondary }}>{attachment.contentType || t("damageWorkflow.common.notAvailable")} · {formatFileSize(attachment.sizeBytes)}</Text><Text style={{ color: Colors.textSecondary }}>{t("damageWorkflow.attachments.uploaded", { id: attachment.uploadedBy, date: formatTimestamp(attachment.uploadedAt, locale) })}</Text>{openError ? <Text style={{ color: Colors.error }}>{openError}</Text> : null}<View style={styles.attachmentActions}><WorkflowButton label={t("damageWorkflow.attachments.open")} onPress={() => void open()} variant="secondary" loading={opening} icon="ExternalLink" /><Pressable accessibilityRole="button" accessibilityLabel={t("damageWorkflow.attachments.refreshUrl")} onPress={onRefresh}><Text style={{ color: Colors.primary, fontWeight: "800" }}>{t("damageWorkflow.attachments.refreshUrl")}</Text></Pressable></View></View>; }

const styles = StyleSheet.create({ screen: { flex: 1, padding: 16 }, content: { gap: 12, paddingBottom: 32 }, titleRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: 10 }, title: { flex: 1, fontSize: 24, fontWeight: "800" }, label: { fontSize: 13, fontWeight: "800", marginTop: 2 }, sectionHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 }, sectionTitle: { fontSize: 17, fontWeight: "800" }, attachment: { borderTopWidth: StyleSheet.hairlineWidth, paddingTop: 10, gap: 4 }, attachmentActions: { gap: 8, marginTop: 4 } });
